# .github/workflows/debug-schedule.yml
name: Debug ETL Schedule

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes (for testing)
  workflow_dispatch:

jobs:
  debug-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Debug timing
        run: |
          echo "=== Debug Information ==="
          echo "Current UTC time: $(date -u)"
          echo "Current local time: $(date)"
          echo "Hour: $(date +%H)"
          echo "Minute: $(date +%M)"
          echo "Minute mod 5: $(($(date +%M) % 5))"
          echo "Minute mod 15: $(($(date +%M) % 15))"
          echo "GitHub event: ${{ github.event_name }}"
          echo "=== Workflow History ==="
          
      - name: Check if multiple schedules trigger
        run: |
          current_minute=$(date +%M)
          echo "Should run trains (every 5 min): $((current_minute % 5 == 0))"
          echo "Should run movements (every 15 min): $((current_minute % 15 == 0))"
          echo "Should run stations (hour 2, min 0): $([[ $(date +%H) -eq 2 && $(date +%M) -eq 0 ]] && echo "true" || echo "false")"